server:
  port: 8090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defualzone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/user/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/user/**